version: "3.7"

networks:
  formzend:

volumes:
  formzend_app:
  formzend_db:
  formzend_redis:

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: passw0rdR0FL
      MYSQL_DATABASE: formzend
    networks:
      - formzend
    volumes:
    - formzend_db:/var/lib/mysql

  nginx:
    image: nginx:alpine
    volumes:
      - formzend_app:/var/www/formzend
      - ./docker/nginx/formzend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - formzend
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    volumes:
      - formzend_app:/var/www/formzend
    env_file:
      - .env.docker
    networks:
      - formzend
    depends_on:
      - db
      - redis

  queue:
    build:
      context: .
      dockerfile: docker/queue.Dockerfile
    env_file:
      - .env.docker
    volumes:
      - formzend_app:/var/www/formzend
    depends_on:
      - app
    networks:
      - formzend

  redis:
    image: redis:alpine
    networks:
      - formzend
    volumes:
    - formzend_redis:/data
