version: "3.7"

networks:
  formzend:

volumes:
  formzend_db:
  formzend_redis:

services:
  db:
    deploy:
      restart_policy:
        condition: on-failure
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: passw0rdR0FL
      MYSQL_DATABASE: formzend
    networks:
      - formzend
    volumes:
      - formzend_db:/var/lib/mysql

  nginx:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    image: nginx:alpine
    volumes:
      - .:/var/www/formzend
      - ./docker/nginx/formzend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - formzend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    image: docker.pkg.github.com/inscrompt/formzend/app:edge
    environment:
      CONTAINER_ROLE: app
    volumes:
      - .:/var/www/formzend
    env_file:
      - .env.docker
    networks:
      - formzend
    depends_on:
      - db
      - redis

  queue:
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    image: docker.pkg.github.com/inscrompt/formzend/app:edge
    environment:
      CONTAINER_ROLE: queue
    env_file:
      - .env.docker
    volumes:
      - .:/var/www/formzend
    depends_on:
      - app
      - redis
    networks:
      - formzend

  redis:
    deploy:
      restart_policy:
        condition: on-failure
    image: redis:alpine
    networks:
      - formzend
    volumes:
    - formzend_redis:/data
